# Generated by Django 5.0.6 on 2024-06-13 20:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('motos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Panne',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('date_signalement', models.DateField()),
                ('etat', models.CharField(choices=[('non_corrigee', 'Non corrigée'), ('corrigee', 'Corrigée')], default='non_corrigee', max_length=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='panne_created_by', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='panne_modified_by', to=settings.AUTH_USER_MODEL)),
                ('moto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='motos.moto')),
            ],
        ),
    ]
