# Generated by Django 5.0.6 on 2024-06-24 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('utilisateurs', '0002_alter_utilisateur_groups_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='utilisateur',
            name='groups',
            field=models.ManyToManyField(blank=True, related_name='utilisateur_groups', to='auth.group'),
        ),
        migrations.AlterField(
            model_name='utilisateur',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, related_name='utilisateur_permissions', to='auth.permission'),
        ),
    ]
